# Generated by Django 3.0.7 on 2020-06-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('numcomentarios', models.IntegerField(blank=True, null=True)),
                ('numvistas', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to='cursos/foto')),
            ],
        ),
    ]
