# Generated by Django 3.0.7 on 2020-06-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='dia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='mes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
