# Generated by Django 3.0.7 on 2020-06-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200607_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
