# Generated by Django 3.0.7 on 2020-06-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portafolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textobienvenida', models.TextField(blank=True, null=True)),
                ('fotofondo', models.ImageField(blank=True, null=True, upload_to='portada/fotofondo')),
                ('textoacerca', models.TextField(blank=True, null=True)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='portada/fotoperfil')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/cv')),
                ('videopresentacion', models.CharField(max_length=150)),
            ],
        ),
    ]
