# Generated by Django 3.0.7 on 2020-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('funciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
