# Generated by Django 3.0.7 on 2020-06-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200613_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['año']},
        ),
        migrations.CreateModel(
            name='temario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=150)),
                ('minutos', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
